/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DMGRJavaInterface */

#ifndef _Included_DMGRJavaInterface
#define _Included_DMGRJavaInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     DMGRJavaInterface
 * Method:    DmgrOpen
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_DMGRJavaInterface_DmgrOpen
  (JNIEnv *, jclass, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
