
#gcc -c -I /opt/digilent.adept.sdk_2.1.1/inc/ -I /usr/lib/jvm/java-1.6.0-openjdk/include/ -I ../include/ -L /usr/local/lib64/digilent/adept/ dmgrImp.cpp -ldepp -ldmgr
CC=gcc
INCD=-I /opt/digilent.adept.sdk_2.1.1/inc/ -I /usr/lib/jvm/java-1.6.0-openjdk/include/ -I ../include/
LIBD=-L /usr/local/lib64/digilent/adept/
LIBS=-ldepp -ldmgr

